EmailBot/urls.py
from django.contrib import admin
from django.urls import include,path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('tasklog/',include('tasklog.urls')),
]

tasklog/urls.py
from django.urls import path

from . import views

app_name='tasklog'
urlpatterns = [
    path('',views.IndexView.as_view(),name='index'),
    path('<int:pk>',views.DetailView.as_view(),name='detail'),
    path('addtask/',views.add_task,name='addtask'),
    path('sendemail/',views.send_email,name='sendemail'),
]

tasklog/models.py
from django.db import models

# Create your models here.
class Task(models.Model):
    task_type_choices = (
        ('d','done'),
        ('t','todo'),
    )
    title = models.CharField(max_length=200)
    content = models.TextField(blank=True)
    date=models.DateTimeField('date added',auto_now_add=True)
    done_date=models.DateTimeField('date done',null=True,blank=True)
    task_type = models.TextField(choices=task_type_choices)

    def __str__(self):
        return self.title

tasklog/forms.py
from django.forms import ModelForm
from .models import Task

class TaskForm(ModelForm):
    class Meta:
        model = Task
        fields = ["title","content","task_type"]
    



# from django import forms

# class TaskForm(forms.Form):
#     title = forms.CharField(label='title',max_length=200)
#     content = forms.Textarea()

tasklog/views.py
# _*_ coding: utf-8 _*_
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404,render
from django.urls import reverse
from django.views import generic
from django.core.mail import send_mail
from django.conf import settings
from email.header import Header
import datetime

from .models import Task
from .forms import TaskForm

class IndexView(generic.ListView):
    template_name = 'tasklog/index.html'
    current_week = datetime.date.today().isocalendar()[1]
    queryset = Task.objects.filter(date__week = current_week, task_type__exact='d')
    def get_context_data(self,**kwargs):
        context = super(IndexView,self).get_context_data(**kwargs)
        context['this_week_tasks_done'] = self.queryset
        context['this_week_tasks_todo'] = Task.objects.filter(task_type__exact='t').order_by('date')
        return context


class DetailView(generic.DeleteView):
    model = Task
    object_name='task'
    template_name = 'tasklog/detail.html'

def add_task(request):
    if request.method == 'POST':
        form = TaskForm(request.POST)

        if form.is_valid():
            # add to datebase
            form.save()
            return HttpResponseRedirect('/tasklog/')
    else:
        form = TaskForm()
    
    return render(request,'tasklog/addtask.html',{'form':form})

def send_email(request):
    current_week = datetime.date.today().isocalendar()[1]
    this_week_tasks_done = Task.objects.filter(date__week=current_week,task_type__exact='d')
    next_week_tasks_todo = Task.objects.filter(task_type__exact='t').order_by('date')[:2]

    message_content = "李老师，现在向您汇报本周工作和下周工作计划：\n\n本周工作：\n"
    print(type(this_week_tasks_done))
    i=0
    for task in this_week_tasks_done:
        message_content += "    "+ str(i+1) +". " + str(task.title)+"\n"
        message_content += "        "+str(task.content) +"\n"
        i+=1
    
    message_content += "\n" + "下周工作计划:\n"
    i=0
    for task in next_week_tasks_todo:
        message_content += "    "+ str(i+1) +". " + str(task.title)+"\n"
        i+=1

    message_content += "\n\n\n丁鹏辉"
    message_subject = "丁鹏辉_每周汇报_" + str(datetime.date.today())
    message_from = Header('丁鹏辉','utf-8').encode() + ' <919479850@qq.com>'
    message_to   = Header('李俊老师','utf-8').encode()+ ' <220184402@seu.edu.cn>'
    send_mail(message_subject,message_content,message_from,(message_to,))
















# ────────────────────────────────────────────────────────────────────────────────


# from django.shortcuts import render,get_object_or_404
# from .models import Task
# import datetime

# def index(request):
#     # 获取当前{week}的tasks，然后展示
#     current_week = datetime.datetime.now().isocalendar()[1]
    
#     # 警告! 这里的todo逻辑有问题，暂时不修改
#     this_week_tasks = Task.objects.filter(date__week=current_week)
#     this_week_tasks_done = this_week_tasks.filter(task_type__exact='d')
#     this_week_tasks_todo = this_week_tasks.filter(task_type__exact='t')
#     context = {
#         'this_week_tasks_done':this_week_tasks_done,
#         'this_week_tasks_todo':this_week_tasks_todo,
#     }
#     print(this_week_tasks[0])
#     return render(request,'tasklog/index.html',context)

# def detail(request,pk):
#     #获取某个task的detail信息

#     # try:
#     #     task=Task.objects.get(pk=pk)
#     # except Task.DoesNotExist:
#     #     raise Http404('没有指定task!')
#     # return render(request,'tasklog/detail.html',{'task':task})

#     # ─── EASIER WAY ─────────────────────────────────────────────────────────────────

#     task = get_object_or_404(Task,pk=pk)
#     return render(request,'tasklog/detail.html',{'task':task})
#     # ────────────────────────────────────────────────────────────────────────────────



# def addTask(request):
#     #添加TASK的VIEW
#     return render(request,'tasklog/addtask.html')

# def changeTask(request):
#     # 修改todo为done
#     pass

tasklog/templates/tasklog/addtask.html
{% extends "tasklog/base.html" %}

{% block page-header %}
<h2>添加一项工作</h2>
<p>填写下面的表单来添加一项工作</p>
{% endblock %}


{% block content %}
<div class="col-md-4"></div>
<div class="col-md-8">
    <div class="input-group">
        <form action="{% url 'tasklog:addtask' %}" method="POST">
            {% csrf_token %}
            <span class="input-group-addon">标题</span>
            <input type="text" name="title" class="form-control" id="id_title" placeholder="我想要做的事是..." maxlength="200"
                required=''>

            <span class="input-group-addon">正文</span>
            <input name="content" type="text" class="form-control content" id="id_content" placeholder="要补充的详细情况...">

            <span class="input-group-addon">类型</span>
            <select name="task_type" class="form-control" id="id_task">
                <option value="d">已完成</option>
                <option value="t" selected>待办事项</option>
            </select>
            <div class="input-group-btn">
                <button class="btn btn-lg  btn-block" type="submit" value="Submit">Submit</button>
            </div>
        </form>
    </div>
</div>
{% endblock %}

tasklog/templates/tasklog/base.html
<!DOCTYPE html>
<html lang="zh-CN">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- 上述3个meta标签*必须*放在最前面，任何其他内容都*必须*跟随其后！ -->
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../favicon.ico">

    <title>TASKLOG</title>

    <!-- Bootstrap core CSS -->
    <link href="https://cdn.bootcss.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">

    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <link href="../../assets/css/ie10-viewport-bug-workaround.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="navbar.css" rel="stylesheet">

    <!-- Just for debugging purposes. Don't actually copy these 2 lines! -->
    <!--[if lt IE 9]><script src="../../assets/js/ie8-responsive-file-warning.js"></script><![endif]-->
    <script src="../../assets/js/ie-emulation-modes-warning.js"></script>

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://cdn.bootcss.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://cdn.bootcss.com/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>

  <body>

    <div class="container">

      <!-- Static navbar -->
      <nav class="navbar">
        <div class="container-fluid">
          <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="#">TASKLOG</a>
          </div>
          <div id="navbar" class="navbar-collapse collapse">
            <ul class="nav navbar-nav navbar-right">
              <li class="active"><a href="#">Home</a></li>
              <li><a href="#">About</a></li>
              <li><a href="#">Contact</a></li>
            </ul>
          </div><!--/.nav-collapse -->
        </div><!--/.container-fluid -->
      </nav>

      <!-- Main component for a primary marketing message or call to action -->

      <div class="jumbotron">
        {% block page-header %} {% endblock %}
      </div>


      
      <div class="row">
        {% block content %}{% endblock %}
      </div>

    </div> <!-- /container -->


    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://cdn.bootcss.com/jquery/1.12.4/jquery.min.js"></script>
    <script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery.min.js"><\/script>')</script>
    <script src="https://cdn.bootcss.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="../../assets/js/ie10-viewport-bug-workaround.js"></script>
  </body>
</html>

tasklog/templates/tasklog/common.html
{% extends "tasklog/base.html" %}

{% block page-header %}
{% endblock %}


{% block content %}
{% endblock %}

tasklog/templates/tasklog/detail.html
<h1>{{ task.title }}</h1>

<form>
<input type="text" name="content" value="{{ task.content }}">
<input type="text" name="task-type" value="{{ task.task_type }}">
</form>

tasklog/templates/tasklog/index.html
{% extends "tasklog/base.html" %}

{% block page-header %}
<h2>本周的工作进程</h2>
<p>这个页面展示了本周已完成的进程和未完成的进程</p>
<p><a href="{% url 'tasklog:addtask' %}">添加一项工作</a></p>
<p><a href="{% url 'tasklog:sendemail' %}">发送邮件</a></p>
{% endblock %}


{% block content %}
<div class="col-md-6">
        <h3>TODO_LIST</h3>
        {% if this_week_tasks_todo %}
            <ul class="list-group">
                {% for task in this_week_tasks_todo %}
                <a class="list-group-item" href="{% url 'tasklog:detail' task.pk %}">{{ task.title }}</a>
                {% endfor%}
            </ul>
        {% else %}
            <p> WHAAAAAT YOU DONT HAVE ANY LEFT TODO?? </p>
            <P> come and add some ! </P>
        {% endif %}
</div>
<div class="col-md-1"></div>
<div class="col-md-4">
        <h3>已完成的工作</h3>
        {% if this_week_tasks_done %}
            <ul class="list-group">
                {% for task in this_week_tasks_done %}
                <a class="list-group-item" href="{% url 'tasklog:detail' task.pk %}">{{ task.title }}</a>
                {% endfor%}
            </ul>
        {% else %}
            <p> no available task </p>
        {% endif %}
</div>




{% endblock %}